### ISSUE TITLE
Book Binder reverts the enchantment level to maximal on the config

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3247]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Book Binder reverts the enchantment level to maximal on the config if your enchanted book exceeds it.

https://discord.com/channels/565557184348422174/565569972697301020/886602140280324136

### 📑 Reproduction Steps

1. Set `bypass-vanilla-max-level: false` for vanilla cap or `custom-max-level: 10` and `has-custom-max-level: true`
2. Use book binder
3. Put an enchantment that exceeds vanilla limit or maximum level cap on config
4. Wait it process
5. It will revert the enchantment to maximum configured level (vanilla/config).

### 💡 Expected Behavior

Book binder should not take the items and revert the enchantment to maximum configured level (vanilla/config). It should just not work.

### 📷 Screenshots / Videos

https://youtu.be/lW0-6tL46SM

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> sf versions
[21:07:57 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-259 (MC: 1.17.1)
Slimefun DEV - 968 (git 79c6c139)
Metrics-Module #28
Java 16

No Addons installed
> pl
[21:07:57 INFO]: Plugins (3): Slimefun, Vault, VoidGen
> ver
[21:07:58 INFO]: Checking version, please wait...
[21:08:00 INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)
You are running the latest version
Previous version: git-Paper-250 (MC: 1.17.1)
```

**Comment by JustAHuman-xD** [comment]
Is this fixed in the lastest build with the book binder changes?

**Comment by Boomer-1** [comment]
I just tested it and it is still an issue. I set bypass vanilla to false, put in an unbreaking X and an unbreaking 3 and got an unbreaking 3 out.

**Comment by Boomer-1** [comment]
Alessio did a similar fix to this issue with the auto enchanters
